server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: flow-manager
          uri: lb://flow-manager
          predicates:
            - Path=/api/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/fileconverter

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/

management:
  endpoints:
    web:
      exposure:
        include: gateway
  endpoint:
    gateway:
      enabled: true

logging:
  level:
    org.springframework.security: DEBUG